version:'3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: nextjs_app
    ports:
      - "3000:3000"
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgresdb
      depends_on:
        - postgres
